/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../core";
import { AxleApi } from "@fern-api/axle";
import urlJoin from "url-join";
import * as serializers from "../../../../serialization";
import * as errors from "../../../../errors";

export declare namespace Tokens {
    interface Options {
        environment: string;
        apiKey?: core.Supplier<string>;
    }
}

export class Tokens {
    constructor(private readonly options: Tokens.Options) {}

    public async exchangeToken(request: AxleApi.ExchangeTokenRequest): Promise<AxleApi.ExchangeTokenResponse> {
        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, "token/exchange"),
            method: "POST",
            headers: {
                X_API_KEY: await core.Supplier.get(this.options.apiKey),
            },
            body: await serializers.ExchangeTokenRequest.jsonOrThrow(request),
        });
        if (_response.ok) {
            return await serializers.ExchangeTokenResponse.parseOrThrow(
                _response.body as serializers.ExchangeTokenResponse.Raw,
                { allowUnknownKeys: true }
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AxleApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AxleApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.AxleApiTimeoutError();
            case "unknown":
                throw new errors.AxleApiError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
