/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Axle from "../../../..";

export interface StartIgnitionRequest {
    /** The URI we should direct the user to after authenticating successfully. */
    redirectUri?: string;
    /** The URI we should send updates about this session or the resulting account to. */
    webhookUri?: string;
    user?: Axle.User;
    /** Optional object to store ephermeral information about the session, such as `reservationTime`. Will be returned in webhook events. */
    metadata?: Record<string, unknown>;
}
