/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { AxleApi } from "@fern-api/axle";

export interface StartIgnitionRequest {
    redirectUri?: string;
    webhookUri?: string;
    user?: AxleApi.User;
    metadata?: Record<string, unknown>;
}
