/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class AxleApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, AxleApiTimeoutError.prototype);
    }
}
