/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class AxleTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, AxleTimeoutError.prototype);
    }
}
