/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../core";
import * as Axle from "../../..";
import urlJoin from "url-join";
import * as serializers from "../../../../serialization";
import * as errors from "../../../../errors";

export declare namespace Ignition {
    interface Options {
        environment: string;
        apiKey?: core.Supplier<string | undefined>;
        clientId: core.Supplier<string>;
        clientSecret: core.Supplier<string>;
    }
}

export class Ignition {
    constructor(protected readonly options: Ignition.Options) {}

    public async startIgnition(request: Axle.StartIgnitionRequest = {}): Promise<Axle.StartIgnitionResponse> {
        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, "ignition"),
            method: "POST",
            headers: {
                "x-client-id": await core.Supplier.get(this.options.clientId),
                "x-client-secret": await core.Supplier.get(this.options.clientSecret),
                "x-access-token": await core.Supplier.get(this.options.apiKey),
            },
            contentType: "application/json",
            body: await serializers.StartIgnitionRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: 60000,
        });
        if (_response.ok) {
            return await serializers.StartIgnitionResponse.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
            });
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AxleError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AxleError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.AxleTimeoutError();
            case "unknown":
                throw new errors.AxleError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
