/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An Account represents an account with an insurance carrier and includes high-level account information (e.g. name) and any Policy objects associated with the Account.
 */
export interface Account {
    id: string;
    carrier: string;
    firstName: string;
    lastName: string;
    phone?: string;
    email?: string;
    policies: string[];
    createdAt: string;
    modifiedAt: string;
    refreshedAt: string;
}
