/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Address {
    addressLine1?: string;
    country?: string;
    addressLine2?: string;
    state?: string;
    city?: string;
    postalCode?: string;
}
