/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Axle } from "@fern-api/axle";

export interface Carrier {
    id: string;
    name: string;
    domain: string;
    address: Axle.Address;
    phone: string;
    logoUrl?: string;
    modifiedAt: string;
}
