/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CoverageCode = "BI" | "PD" | "UMBI" | "UMPD" | "UIMBI" | "UIMPD" | "COLL" | "COMP";

export const CoverageCode = {
    Bi: "BI",
    Pd: "PD",
    Umbi: "UMBI",
    Umpd: "UMPD",
    Uimbi: "UIMBI",
    Uimpd: "UIMPD",
    Coll: "COLL",
    Comp: "COMP",
} as const;
