/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { AxleApi } from "@fern-api/axle";

export interface Error {
    success?: AxleApi.Success;
    /** Provides a reason for why the operation failed, if available. */
    message?: string;
}
