/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Axle from "..";

export interface Error_ {
    success?: Axle.Success;
    /** Provides a reason for why the operation failed, if available. */
    message?: string;
}
