/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Axle from "..";

/**
 *
 */
export interface ExchangeTokenResponse {
    success: Axle.Success;
    data: Axle.ExchangeTokenResponseData;
}
