/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { AxleApi } from "@fern-api/axle";

/**
 *
 */
export interface ExchangeTokenResponse {
    success: AxleApi.Success;
    data: AxleApi.ExchangeTokenResponseData;
}
