/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ExchangeTokenResponseData {
    /** The token required for access to the requested Account and Policy objects. */
    accessToken: string;
    /** The unique id for the Account object. */
    account: string;
    /** List of unique ids for the Policy objects. If Ignition is configured to select a single policy (as is the default), the list will only contain 1 item. */
    policies: unknown[];
}
