/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Axle } from "@fern-api/axle";

export interface GetAccountResponse {
    success?: Axle.Success;
    data?: Axle.Account;
}
