/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Axle } from "@fern-api/axle";

export interface GetCarriersResponse {
    success?: Axle.Success;
    data?: Axle.Carrier[];
}
