/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { AxleApi } from "@fern-api/axle";

export interface GetPolicyResponse {
    success?: AxleApi.Success;
    data?: AxleApi.Policy;
}
