/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Insured {
    property?: string;
    firstName: string;
    lastName: string;
    dateOfBirthYear?: string;
    licenseNo?: string;
    licenseState?: string;
    licenseStatus?: string;
    dateOfBirth?: string;
    type?: string;
}
