/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Axle from "..";

/**
 * A Policy represents a specific policy associated with an Account and includes high-level policy information (e.g. policy number) and any children objects (e.g., coverages) associated with the policy.
 */
export interface Policy {
    id: string;
    account: string;
    type: Axle.PolicyType;
    carrier: string;
    policyNumber: string;
    isActive: boolean;
    effectiveDate: string;
    expirationDate: string;
    address: Axle.Address;
    /** */
    coverages: Axle.Coverage[];
    /** */
    properties: Axle.Property[];
    /** */
    insureds: Axle.Insured[];
    /** */
    thirdParties: Axle.ThirdParty[];
    createdAt: string;
    modifiedAt: string;
    refreshedAt: string;
}
