/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PolicyType = "auto" | "motorcycle";

export const PolicyType = {
    Auto: "auto",
    Motorcycle: "motorcycle",
} as const;
