/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { AxleApi } from "@fern-api/axle";

/**
 * A Policy represents a specific policy associated with an Account and includes high-level policy information (e.g. policy number) and any children objects (e.g., coverages) associated with the policy.
 */
export interface Policy {
    id: string;
    account: string;
    type: AxleApi.PolicyType;
    carrier: string;
    policyNumber: string;
    isActive: boolean;
    effectiveDate: string;
    expirationDate: string;
    address: AxleApi.Address;
    /** */
    coverages: AxleApi.Coverage[];
    /** */
    properties: AxleApi.Property[];
    /** */
    insureds: AxleApi.Insured[];
    /** */
    thirdParties: AxleApi.ThirdParty[];
    createdAt: string;
    modifiedAt: string;
    refreshedAt: string;
}
