/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Axle from "..";

export interface Property {
    id: string;
    type: Axle.PropertyType;
    data: Axle.Vehicle;
}
