/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Axle } from "@fern-api/axle";

export interface Property {
    id: string;
    type: Axle.PropertyType;
    data: Axle.Vehicle;
}
