/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { AxleApi } from "@fern-api/axle";

export interface Property {
    id: string;
    type: AxleApi.PropertyType;
    data: AxleApi.Vehicle;
}
