/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface StartIgnitionResponseData {
    /** The url you should direct the user to to link their account. */
    ignitionUri: string;
    /** The unique ID for the ignition session. */
    ignitionToken: string;
}
