/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { AxleApi } from "@fern-api/axle";

export interface ThirdParty {
    property?: string;
    type: AxleApi.ThirdPartyType;
    name: string;
    address?: AxleApi.Address;
}
