/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ThirdPartyType = "lienholder" | "lessor" | "interest";

export const ThirdPartyType = {
    Lienholder: "lienholder",
    Lessor: "lessor",
    Interest: "interest",
} as const;
