/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Axle from "..";

export interface ThirdParty {
    property?: string;
    type: Axle.ThirdPartyType;
    name: string;
    address?: Axle.Address;
}
