/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { AxleApi } from "@fern-api/axle";
import * as core from "../../core";

export const CoverageCode: core.serialization.Schema<serializers.CoverageCode.Raw, AxleApi.CoverageCode> =
    core.serialization.enum_(["BI", "PD", "UMBI", "UMPD", "UIMBI", "UIMPD", "COLL", "COMP"]);

export declare namespace CoverageCode {
    type Raw = "BI" | "PD" | "UMBI" | "UMPD" | "UIMBI" | "UIMPD" | "COLL" | "COMP";
}
