/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { AxleApi } from "@fern-api/axle";
import * as core from "../../core";

export const Error: core.serialization.ObjectSchema<serializers.Error.Raw, AxleApi.Error> = core.serialization.object({
    success: core.serialization.lazy(async () => (await import("..")).Success).optional(),
    message: core.serialization.string().optional(),
});

export declare namespace Error {
    interface Raw {
        success?: serializers.Success.Raw | null;
        message?: string | null;
    }
}
