/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Axle from "../../api";
import * as core from "../../core";

export const ExchangeTokenResponseData: core.serialization.ObjectSchema<
    serializers.ExchangeTokenResponseData.Raw,
    Axle.ExchangeTokenResponseData
> = core.serialization.object({
    accessToken: core.serialization.string(),
    account: core.serialization.string(),
    policies: core.serialization.list(core.serialization.unknown()),
});

export declare namespace ExchangeTokenResponseData {
    interface Raw {
        accessToken: string;
        account: string;
        policies: unknown[];
    }
}
