/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { AxleApi } from "@fern-api/axle";
import * as core from "../../core";

export const GetPolicyResponse: core.serialization.ObjectSchema<
    serializers.GetPolicyResponse.Raw,
    AxleApi.GetPolicyResponse
> = core.serialization.object({
    success: core.serialization.lazy(async () => (await import("..")).Success).optional(),
    data: core.serialization.lazyObject(async () => (await import("..")).Policy).optional(),
});

export declare namespace GetPolicyResponse {
    interface Raw {
        success?: serializers.Success.Raw | null;
        data?: serializers.Policy.Raw | null;
    }
}
