/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Axle from "../../api";
import * as core from "../../core";

export const PolicyType: core.serialization.Schema<serializers.PolicyType.Raw, Axle.PolicyType> =
    core.serialization.enum_(["auto", "motorcycle"]);

export declare namespace PolicyType {
    type Raw = "auto" | "motorcycle";
}
