/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { AxleApi } from "@fern-api/axle";
import * as core from "../../core";

export const Property: core.serialization.ObjectSchema<serializers.Property.Raw, AxleApi.Property> =
    core.serialization.object({
        id: core.serialization.string(),
        type: core.serialization.lazy(async () => (await import("..")).PropertyType),
        data: core.serialization.lazyObject(async () => (await import("..")).Vehicle),
    });

export declare namespace Property {
    interface Raw {
        id: string;
        type: serializers.PropertyType.Raw;
        data: serializers.Vehicle.Raw;
    }
}
