/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { Axle } from "@fern-api/axle";
import * as core from "../../core";

export const StartIgnitionResponseData: core.serialization.ObjectSchema<
    serializers.StartIgnitionResponseData.Raw,
    Axle.StartIgnitionResponseData
> = core.serialization.object({
    ignitionUri: core.serialization.string(),
    ignitionToken: core.serialization.string(),
});

export declare namespace StartIgnitionResponseData {
    interface Raw {
        ignitionUri: string;
        ignitionToken: string;
    }
}
