/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { AxleApi } from "@fern-api/axle";
import * as core from "../../core";

export const Success: core.serialization.Schema<serializers.Success.Raw, AxleApi.Success> =
    core.serialization.boolean();

export declare namespace Success {
    type Raw = boolean;
}
