/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { Axle } from "@fern-api/axle";
import * as core from "../../core";

export const User: core.serialization.ObjectSchema<serializers.User.Raw, Axle.User> = core.serialization.object({
    id: core.serialization.string(),
    firstName: core.serialization.string().optional(),
    lastName: core.serialization.string().optional(),
    email: core.serialization.string().optional(),
    phone: core.serialization.string().optional(),
});

export declare namespace User {
    interface Raw {
        id: string;
        firstName?: string | null;
        lastName?: string | null;
        email?: string | null;
        phone?: string | null;
    }
}
