/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "./core";
import { Ignition } from "./api/resources/ignition/client/Client";
import { Tokens } from "./api/resources/tokens/client/Client";
import { Accounts } from "./api/resources/accounts/client/Client";
import { Policies } from "./api/resources/policies/client/Client";
import { Carriers } from "./api/resources/carriers/client/Client";

export declare namespace AxleClient {
    interface Options {
        environment: string;
        apiKey?: core.Supplier<string | undefined>;
        clientId: core.Supplier<string>;
        clientSecret: core.Supplier<string>;
    }
}

export class AxleClient {
    constructor(protected readonly options: AxleClient.Options) {}

    protected _ignition: Ignition | undefined;

    public get ignition(): Ignition {
        return (this._ignition ??= new Ignition(this.options));
    }

    protected _tokens: Tokens | undefined;

    public get tokens(): Tokens {
        return (this._tokens ??= new Tokens(this.options));
    }

    protected _accounts: Accounts | undefined;

    public get accounts(): Accounts {
        return (this._accounts ??= new Accounts(this.options));
    }

    protected _policies: Policies | undefined;

    public get policies(): Policies {
        return (this._policies ??= new Policies(this.options));
    }

    protected _carriers: Carriers | undefined;

    public get carriers(): Carriers {
        return (this._carriers ??= new Carriers(this.options));
    }
}
