/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const AxleEnvironment = {
    Production: "https://api.axle.insure",
    Sandbox: "https://sandbox.axle.insure",
} as const;

export type AxleEnvironment = typeof AxleEnvironment.Production | typeof AxleEnvironment.Sandbox;
