/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ExchangeTokenRequest {
    /** The authorization code obtained after a user successfully links their account via Ignition. Returned as a query parameter at the redirectUri. */
    authCode: string;
}
